version: '3.8'

services:
  go-messaging:
    image: afiffaizianur/go-messaging:latest
    container_name: go-messaging-app
    ports:
      - "8080:8080"
    environment:
      - ENV=production  # Don't try to load .env file in Docker
      - PORT=8080
      - MODE=debug
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    networks:
      - messaging-network

networks:
  messaging-network:
    driver: bridge