#!/bin/bash

# Telegram User ID Helper Script
# This script helps you get your Telegram User ID for the admin setup

echo "🤖 Go Messaging Bot - Telegram User ID Helper"
echo "=============================================="
echo ""
echo "To set up admin users, you need your Telegram User ID."
echo ""
echo "📱 Method 1: Using @userinfobot"
echo "1. Open Telegram"
echo "2. Search for @userinfobot"
echo "3. Start a chat with the bot"
echo "4. Send any message"
echo "5. The bot will reply with your User ID"
echo ""
echo "📱 Method 2: Using @RawDataBot"
echo "1. Open Telegram"
echo "2. Search for @RawDataBot"
echo "3. Start a chat with the bot"
echo "4. Send any message"
echo "5. Look for 'id' field in the response"
echo ""
echo "📱 Method 3: Using Web Telegram"
echo "1. Open https://web.telegram.org"
echo "2. Log in to your account"
echo "3. Look at the URL - your ID is after 'u' parameter"
echo "   Example: https://web.telegram.org/k/#@username -> your ID"
echo ""
echo "🔧 Once you have your User ID:"
echo "1. Edit init_database.sql"
echo "2. Replace 123456789 with your actual Telegram User ID"
echo "3. Run: psql -d go_messaging -f init_database.sql"
echo ""
echo "💡 For multiple admins, add more INSERT statements with different User IDs"
echo ""
echo "Example:"
echo "INSERT INTO users (telegram_user_id, username, first_name, role, approval_status, approved_at) VALUES"
echo "(YOUR_USER_ID, 'your_username', 'Your Name', 'admin', 'approved', NOW());"
echo ""
echo "🚀 After setup, message your bot with /admin to access the admin panel!"
echo ""
read -p "Press Enter to continue..."
